In [2]:
import pandas as pd

df = pd.read_excel('dati-canzoni-spotify-sanremo-1951-2023.xlsx')

In [3]:
display(df)

,Canzone,Artista,Anno_ultimo_rilascio,Durata (min),Popolarità,URL immagine album
0,Lasciami cantare una canzone,Achille Togliani,2012,3.448950,20,https://i.scdn.co/image/ab67616d0000b27305045a...
1,Vecchio scarpone,I Girasoli,2011,3.033250,26,https://i.scdn.co/image/ab67616d0000b273ee46e2...
2,Vecchia villa comunale,Gino Latilla,2015,3.948667,0,https://i.scdn.co/image/ab67616d0000b2734c3955...
3,No Pierrot,Aurelio Fierro,2009,3.661483,0,https://i.scdn.co/image/ab67616d0000b2739f58a2...
4,Il passerotto,Ciansunier,2017,2.712433,3,https://i.scdn.co/image/ab67616d0000b273fe1ca7...
...,...,...,...,...,...,...
1577,Polvere,Tedua,2020,4.216517,63,https://i.scdn.co/image/ab67616d0000b273773f82...
1578,Sali (canto dell'anima),Anna Oxa,2023,4.215183,42,https://i.scdn.co/image/ab67616d0000b2739d992d...
1579,Stupido,Massimo Pericolo,2021,3.123850,67,https://i.scdn.co/image/ab67616d0000b2734cc0a9...
1580,Egoista,Shari,2023,2.887967,45,https://i.scdn.co/image/ab67616d0000b273edd542...
1581,Cause perse,Sethu,2023,2.350867,44,https://i.scdn.co/image/ab67616d0000b2736d2f73...

In [4]:
#Iteriamo ogni colonna del DataFrame
for column in df.columns:
    #Somiamo i valori nulli (i dati booleani vengono interpretati come 1 e 0)
    nan_count = df[column].isna().sum()
    #calcoliamo la percentuale
    nan_percentage = round((nan_count/df.shape[0])*100, 2)
    print(f'{column} contains {nan_count} NaN values, {nan_percentage}% of all rows.')

Canzone contains 0 NaN values, 0.0% of all rows.
Artista contains 0 NaN values, 0.0% of all rows.
Anno_ultimo_rilascio contains 0 NaN values, 0.0% of all rows.
Durata (min) contains 0 NaN values, 0.0% of all rows.
Popolarità contains 0 NaN values, 0.0% of all rows.
URL immagine album contains 0 NaN values, 0.0% of all rows.

In [5]:
df_gender = pd.read_excel('dati-artisti-conduzioni-sanremo - 1951 - 2023.xlsx')

In [6]:
df_gender

,n_edizione,anno,nome,ruolo,share_ruolo,genere,note,numero componenti team
0,1,1951,Achille Togliani,Artista,1.0,M,NaN,1
1,1,1951,Delfina Fasano,Artista,1.0,F,Duo Fasano,2
2,1,1951,Giulio Razzi,Direzione artistica,1.0,M,NaN,1
3,1,1951,Nilla Pizzi,Artista,1.0,F,NaN,1
4,1,1951,Nunzio Filogamo,Conduzione,1.0,M,NaN,1
...,...,...,...,...,...,...,...,...
3827,73,2023,Gianni Morandi,Conduzione,1.0,M,NaN,1
3828,73,2023,Chiara Ferragni,Co-conduzione,1.0,F,NaN,1
3829,73,2023,Francesca Fagnani,Co-conduzione,1.0,F,NaN,1
3830,73,2023,Paola Egonu,Co-conduzione,1.0,F,NaN,1
3831,73,2023,Chiara Francini,Co-conduzione,1.0,F,NaN,1

In [7]:
df_gender['anno'] = pd.to_datetime(df_gender['anno'], format='%Y')

In [8]:
df_gender['anno'].dtype

dtype('<M8[ns]')

In [11]:
with pd.ExcelWriter('dati-artisti-conduzioni-sanremo - 1951 - 2023.xlsx', engine='xlsxwriter', date_format='yyyy') as writer:
    df_gender.to_excel(writer, index=False)
print("Colonna 'anno' trasformata in formato anno e salvata in 'dati-artisti-conduzioni-sanremo - 1951 - 2023.xlsx'")

Colonna 'anno' trasformata in formato anno e salvata in 'dati-artisti-conduzioni-sanremo - 1951 - 2023.xlsx'

In [15]:
pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.3-py3-none-any.whl.metadata (2.7 kB)
Downloading XlsxWriter-3.2.3-py3-none-any.whl (169 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.3
Note: you may need to restart the kernel to use updated packages.