In [17]:
import pandas as pd

# Specifica il percorso al tuo file
file_path = 'dati-classifica-sanremo-1951-2023.xlsx'

# Carica solo il foglio chiamato "Python"
df_python = pd.read_excel(file_path, sheet_name='Python')
df = pd.read_excel('dati-canzoni-spotify-sanremo-1951-2023.xlsx')

In [18]:
df_python

,Anno,Posizione,Artista,Canzone,Autori
0,1951,1,Nilla Pizzi,Grazie dei fiori,Gian Carlo Testoni e Mario Panzeri
1,1951,2,Nilla Pizzi e Achille Togliani,La luna si veste d'argento,Biri
2,1951,3,Achille Togliani,Serenata a nessuno,Walter Colì
3,1951,F,Achille Togliani e Duo Fasano,Al mercato di Pizzighettone,Aldo Locatelli
4,1951,F,Nilla Pizzi e Achille Togliani,Eco tra gli abeti,Enzo Bonagura
...,...,...,...,...,...
1678,2014,NF,Giuliano Palma,Un bacio crudele,"C. Valli, G. Palma, F. Merigo"
1679,2014,NF,Noemi,Un uomo è un albero,"Noemi, D. Mancino, D. Faini"
1680,2014,NF,Frankie hi-nrg mc,Un uomo è vivo,"F. Di Gesù, C. Galbignani, L. Beccafichi"
1681,2014,NF,Ron,Un abbraccio unico,Ron
1682,2014,NF,Riccardo Sinigallia,Una rigenerazione,"F. Gatti, R. Sinigallia"

In [19]:
df

,Canzone,Artista,Anno_ultimo_rilascio,Durata (min),Popolarità,URL immagine album
0,...e dimmi che non vuoi morire,Patty Pravo,2001,4.492883,49,https://i.scdn.co/image/ab67616d0000b27369cceb...
1,...e la barca tornò sola,Renato Carosone,1995,2.282217,20,https://i.scdn.co/image/ab67616d0000b2739c1b38...
2,1/2 notte,Gino Balerino e la sua Orchestra,2021,3.088517,0,https://i.scdn.co/image/ab67616d0000b2734202a6...
3,"13, storia d'oggi",Al Bano,2014,4.281100,2,https://i.scdn.co/image/ab67616d0000b273550e63...
4,1950,Amedeo Minghi,1983,4.616433,59,https://i.scdn.co/image/ab67616d0000b2732a3356...
...,...,...,...,...,...,...
1577,Wake Up,MoonDeity,2022,2.382333,78,https://i.scdn.co/image/ab67616d0000b273a3a0d9...
1578,Working Late Tonight,Dennis Kuo,2018,7.316667,5,https://i.scdn.co/image/ab67616d0000b273d6f2f0...
1579,Yanez[22],Relaxing Music by Finjus Yanez,2022,2.147533,0,https://i.scdn.co/image/ab67616d0000b27300ef0f...
1580,Zucchero,Zucchero,1995,4.832217,55,https://i.scdn.co/image/ab67616d0000b273777bc2...
1581,Zucchero e pepe,Bruno Rosettani,2014,3.173433,21,https://i.scdn.co/image/ab67616d0000b273287e55...

In [33]:
# Copie di lavoro per evitare modifiche agli originali
df_python_clean = df_python.copy()
df_clean = df.copy()

# Normalizza le colonne chiave per confronti accurati (rimuove spazi e mette in minuscolo)
for col in ['Canzone', 'Artista']:
    df_python_clean[col] = df_python_clean[col].str.strip().str.lower()
    df_clean[col] = df_clean[col].str.strip().str.lower()

# Esegui il merge mantenendo tutte le colonne di df_python + aggiunta di Popolarità
df_python_clean = df_python_clean.merge(
    df_clean[['Artista', 'Canzone', 'Popolarità' ]],
    on=['Artista', 'Canzone'],
    how='left'
)

# Visualizza le prime righe per controllo
print(df_python_clean)

      Anno Posizione                         Artista  \
0     1951         1                     nilla pizzi
1     1951         2  nilla pizzi e achille togliani
2     1951         3                achille togliani
3     1951         F   achille togliani e duo fasano
4     1951         F  nilla pizzi e achille togliani
...    ...       ...                             ...
1689  2014        NF                  giuliano palma
1690  2014        NF                           noemi
1691  2014        NF               frankie hi-nrg mc
1692  2014        NF                             ron
1693  2014        NF             riccardo sinigallia

                          Canzone                                    Autori  \
0                grazie dei fiori        Gian Carlo Testoni e Mario Panzeri
1      la luna si veste d'argento                                      Biri
2              serenata a nessuno                               Walter Colì
3     al mercato di pizzighettone                            Aldo Locatelli
4               eco tra gli abeti                             Enzo Bonagura
...                           ...                                       ...
1689             un bacio crudele             C. Valli, G. Palma, F. Merigo
1690          un uomo è un albero               Noemi, D. Mancino, D. Faini
1691               un uomo è vivo  F. Di Gesù, C. Galbignani, L. Beccafichi
1692           un abbraccio unico                                       Ron
1693            una rigenerazione                   F. Gatti, R. Sinigallia

      Popolarità
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
...          ...
1689        12.0
1690        10.0
1691        18.0
1692         9.0
1693        10.0

[1694 rows x 6 columns]

In [13]:
df_python_clean.to_excel('dati-classifica-popolarita-sanremo-1951-2023.xlsx',index=False)

In [34]:
#Iteriamo ogni colonna del DataFrame
for column in df_python_clean.columns:
    #Somiamo i valori nulli (i dati booleani vengono interpretati come 1 e 0)
    nan_count = df_python_clean[column].isna().sum()
    #calcoliamo la percentuale
    nan_percentage = round((nan_count/df_python_clean.shape[0])*100, 2)
    print(f'{column} contains {nan_count} NaN values, {nan_percentage}% of all rows.')

Anno contains 0 NaN values, 0.0% of all rows.
Posizione contains 0 NaN values, 0.0% of all rows.
Artista contains 0 NaN values, 0.0% of all rows.
Canzone contains 0 NaN values, 0.0% of all rows.
Autori contains 0 NaN values, 0.0% of all rows.
Popolarità contains 1164 NaN values, 68.71% of all rows.

In [35]:
df_null_popolarita = df_python_clean[df_python_clean['Popolarità'].isnull()]

In [36]:
df_null_popolarita

,Anno,Posizione,Artista,Canzone,Autori,Popolarità
0,1951,1,nilla pizzi,grazie dei fiori,Gian Carlo Testoni e Mario Panzeri,NaN
1,1951,2,nilla pizzi e achille togliani,la luna si veste d'argento,Biri,NaN
2,1951,3,achille togliani,serenata a nessuno,Walter Colì,NaN
3,1951,F,achille togliani e duo fasano,al mercato di pizzighettone,Aldo Locatelli,NaN
4,1951,F,nilla pizzi e achille togliani,eco tra gli abeti,Enzo Bonagura,NaN
...,...,...,...,...,...,...
1678,2014,13,ron,sing in the rain,"Ron, M. Del Forno",NaN
1679,2014,Escluso,riccardo sinigallia,prima di andare via,"F. Gatti, R. Sinigallia",NaN
1681,2014,NF,francesco sarcina,in questa città,F. Sarcina,NaN
1682,2014,NF,cristiano de andré,invisibili[26],"F. Ferraboschi, C. De André",NaN
1688,2014,NF,raphael gualazzi & the bloody beetroots,tanto ci sei,"G. Sangiorgi, R. Gualazzi, B. Cornelius Rifo",NaN